


<form method="POST" action="<?= $requestUrl ?>/user">
	
<fieldset>
	<legend> Identité et coordonnées </legend>
		<br>
	<label for="lastname">Nom : </label>
	<input type="text" name="lastname" id="lastname">
	
	<br>
	<label for="firstname">Prénom : </label>
	<input type="text" name="firstname" id="firstname">
	
	<br>
	
	<label for="address">Adresse : </label>
	<input type="text" name="address" id="address">
	
	<br>
	<label for="city">Ville : </label>
	<input type="text" name="city" id="city">
	
	<br>
	<label for="zipcode">CP : </label>
	<input type="text" name="zipcode" id="zipcode">
	
	<br>
	<label for="phone">Tel : </label>
	<input type="text" name="phone" id="phone">
	
	<br>

	

</fieldset>


<fieldset>
	<legend> Informations d'authentification </legend>

	<br>
	
	<label for="email">Email : </label>
	<input type="text" name="email" id="email">
	<br>
	<label for="password">Mot de passe : </label>
	<input type="password" name="password" id="password">
	<br>
	
	
</fieldset>
	
	<button type="submit" id="ajouter">Enregistrer</button>

</form>