<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <?php foreach ($products as $product): ?> <tr>
        	<td><img src="<?= $wwwUrl?>/images/meals/<?= $product['image']; ?>" alt="<?= $product["name"]; ?>"> </td>
        	<td>
        		<h2><?= $product["name"]; ?></h2>
        		<p><?= $product["description"]; ?></p>
        	</td>
        	<td>
            <?=  Tools::getPrettyPrice($product['priceHT'], $product["tax"]) ?>
            </td>
        </tr>
    	<?php endforeach; ?>
    </tbody>
</table>