<h2><i class="fa fa-check"></i> Payer la commande</h2>

<section class="invoice">
     <?php $user = UserSession::getUser(); ?>
        <p><strong> <?= $user['firstname'] ." ". $user['lastname'] ?></strong></p>
    <p> <?= $user['address'] ?></p>
    <p><?= $user['zipcode'] ?> <span class="city"><?= $user['city'] ?></span></p>
</section>

<table class="generic-table meal-list">
    <caption>Récapitulatif de la commande</caption>
    <thead>
        <tr>
            <th>Nom</th>
            <th class="number">Quantité</th>
            <th class="number">Prix Unitaire</th>
            <th class="number">Prix Total</th>
        </tr>
    </thead>

        <?php $totalHT = 0?>
        <?php foreach ($orderLines as $orderLine): ?> 
        <tr>
            <td>
                <img src="<?= $wwwUrl ?>/images/meals/<?= $orderLine['image'] ?>" width="25%">
                <em><?= $orderLine['name']?></em>
            </td>
            <td class="number"><?= $orderLine['quantity']?></td>
            <td class="number"><?=  Tools::getPrettyPrice(Tools::getPriceTTC($orderLine['priceHT'])) ?></td>
            <td class="number"><?= Tools::getPrettyPrice(Tools::getPriceTTC($orderLine['priceHT'] * $orderLine['quantity'])) ?></td>
         </tr>
         <?php $totalHT += $orderLine['priceHT'] * $orderLine['quantity'];?> 
        <?php endforeach; ?>
    </tbody>




    <tfoot>
        <tr>
            <td colspan="3">Total HT</td>
            <td><?= Tools::getPriceEur($totalHT) ?></td>
        </tr>
        <tr>
            <td colspan="3">TVA (10 %)</td>
            <td> <?= Tools::getPriceEur($totalHT*0.1) ?> </td>
        </tr>
        <tr>
            <td class="colorful" colspan="3">Total TTC</td>
            <td class="colorful"> <?= Tools::getPriceEur($totalHT*1.1) ?></td>
        </tr>
        <tr class="small-notice">
            <td colspan="4">Commandé le <?=$order['created_at']?></td>
        </tr>
    </tfoot>
</table>

<hr>
<h3>Merci de bien vouloir procéder au paiement de la commande.</h3>
<form class="generic-form" action="<?= $requestUrl ?>/success" method="POST">
    <ul>
        <li>
        <input type="hidden" value="<?=$order['id']?>" name="orderId" >
            <input class="button button-primary" type="submit" value="Payer">
            <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
        </li>
    </ul>
</form>   