

<form method="post" action="">
	
	<fieldset>
		<legend><i class="fa fa-book"></i> Identité et coordonnées </legend>
		<br>
		<label for="lastname">Nom : 
		<input type="text" name="lastname" id="lastname"></label>
		
		<br>
		<label for="firstname">Prénom : 
		<input type="text" name="firstname" id="firstname"></label>
		
		<br>
		<label for="birthday">Date anniversaire : 
		<input type="text" name="birthday" id="birthday"></label>
		

		<br>
		
		<label for="address">Adresse : 
		<input type="text" name="address" id="address"></label>
		
		<br>
		<label for="city">Ville : 
		<input type="text" name="city" id="city"></label>
		
		<br>
		<label for="zipcode">CP : 
		<input type="text" name="zipcode" id="zipcode"></label>
		
		<br>
		<label for="phone">Tel : 
		<input type="text" name="phone" id="phone"></label>
		
		<br>

		

	</fieldset>


	<fieldset>
		<legend><i class="fa fa-lock"></i> Informations d'authentification </legend>

		<br>
		
		<label for="email">Email : 
		<input type="text" name="email" id="email"></label>
		<br>
		<label for="password">Mot de passe : 
		<input type="password" name="password" id="password">
		<br></label>
		
		
	</fieldset>
		
	<input class="button button-primary" type="submit" value="Créer le compte">
	<a class="button button-cancel small" href="/dev/resto/final/index.php">Annuler</a>
		
</form>
