 <h2><i class="fa fa-cutlery"></i> Réservation d'une table</h2>

<form class="generic-form" action="<?=$requestUrl?>/booking" method="POST">
	<fieldset>
		<legend>Informations</legend>
		<ul>
			<li>
				<label for="bookingDay">Date de réservation :</label>
				<select id="bookingDay" name="bookingDay">
					<option></option>
					<?php for($bookingDay = 1; $bookingDay <= 31; $bookingDay++): ?>
						<option value="<?= $bookingDay ?>"><?= $bookingDay ?></option>
					<?php endfor; ?>
				</select>
				<span> / </span>
				<select name="bookingMonth">
					<option></option>
							
							<?php
							$months = [];
							
							$months[1] = "Janvier";
							$months[2] = "Février";
							$months[3] = "Mars";
							$months[4] = "Avril";
							$months[5] = "Mai";
							$months[6] = "Juin";
							$months[7] = "Juillet";
							$months[8] = "Aout";
							$months[9] = "Septembre";
							$months[10] = "Octobre";
							$months[11] = "Novembre";
							$months[12] = "Décembre";


							foreach($months as $key =>$month) {
							  
								echo "<option value='$key'>$month</option>";
							}
						?>
						
					</select> 
				<span> / </span>
				<select name="bookingYear">
                    <option value="<?= date('Y')     ?>"><?= date('Y')     ?></option>
                    <option value="<?= date('Y') + 1 ?>"><?= date('Y') + 1 ?></option>
				</select>
				<span> à </span>
				<select name="bookingHour">
					<?php for($bookingHour = 12; $bookingHour <= 23; $bookingHour++): ?>
						<option value="<?= $bookingHour ?>"><?= $bookingHour ?></option>
					<?php endfor; ?>
				</select>
				<span> : </span>
				<select name="bookingMinute">
					<option value="0">00</option>
					<option value="15">15</option>
					<option value="30">30</option>
					<option value="45">45</option>
				</select>
			</li>
			<li>
				<label for="seat_number">Nombre de couverts :</label>
				<select id="seat_number" name="seat_number">
					<?php for($seat_number = 1; $seat_number <= 8; $seat_number++): ?>
						<option value="<?= $seat_number ?>"><?= $seat_number ?></option>
					<?php endfor; ?>
				</select>
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Réserver">
			<a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
		</li>
	</ul>
</form> 












