 <h2><i class="fa fa-cutlery"></i> Réservation d'une table</h2>

<form class="generic-form" action="/dev/resto/final/index.php/booking" method="POST">
	<fieldset>
		<legend>Informations</legend>
		<ul>
			<li>
				<label for="bookingDay">Date de réservation :</label>
				<select id="bookingDay" name="bookingDay">
					<option></option>
						
					<?php

					for($i = 1; $i <= 31; $i++){
						$i = str_pad($i, 2, 0, STR_PAD_LEFT);
						echo "<option value='$i'>$i</option>";
					}
					
					?>
				</select>
				<span> / </span>
				<select name="bookingMonth">
					<option></option>
							
							<?php
							$months = [];
							
							$months[1] = "Janvier";
							$months[2] = "Février";
							$months[3] = "Mars";
							$months[4] = "Avril";
							$months[5] = "Mai";
							$months[6] = "Juin";
							$months[7] = "Juillet";
							$months[8] = "Aout";
							$months[9] = "Septembre";
							$months[10] = "Octobre";
							$months[11] = "Novembre";
							$months[12] = "Décembre";


							foreach($months as $key =>$month) {
							  
								echo "<option value='$key'>$month</option>";
							}
						?>
						
					</select> 
				<span> / </span>
				<select name="bookingYear">
                    <!-- Construction d'une liste déroulante avec l'année en cours et l'année suivante -->
                    <option value="2018">2018</option>
                    <option value="2019">2019</option>
				</select>
				<span> à </span>
				<select name="bookingHour">

					<option></option>
						
					<?php

					for($i = 12; $i <= 23; $i++){
						$i = str_pad($i, 2, 0, STR_PAD_LEFT);
						echo "<option value='$i'>$i</option>";
					}
					
					?>
				</select>
				<span> : </span>
				<select name="bookingMinute">
					<option value="0">00</option>
					<option value="15">15</option>
					<option value="30">30</option>
					<option value="45">45</option>
				</select>
			</li>
			<li>
				<label for="numberOfSeats">Nombre de couverts :</label>
				<select id="numberOfSeats" name="numberOfSeats">
					<option></option>
						
					<?php

					for($i = 1; $i <= 8; $i++){
						$i = str_pad($i, 2, 0, STR_PAD_LEFT);
						echo "<option value='$i'>$i</option>";
					}
					
					?>
				</select>
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Réserver">
			<a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
		</li>
	</ul>
</form> 











