<h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>
<div class="box-add-article">
<form class="generic-form">
    <fieldset>
        <legend>Ajouter un article</legend>
        <ul>
            <li>
                <label for="product">Nom :</label>
                <select id="product" name="product" width="200px">
                    <?php foreach ($productList as $product): ?>
                    <option value="<?= $product["id"]; ?>"><?= $product["name"]; ?> </option>
                    <?php endforeach; ?>                        
                </select> 
            </li>
        
            <div class="product-info">
     
            </div>   
            <li>
                <label for="quantity">Quantité :</label>
                <input id="quantity" class="quantity" type="number" value="1" maxlength="2" min="0" max="20" name="quantity" data-name="Quantité" data-type="positive-integer" data-required>
            </li>
            <button type="button" id="btn-add"  class="button button-primary no-left-label" >Ajouter</button>
        </ul>
    </fieldset>


    <fieldset>
        <legend>Récapitulatif de la commande</legend>
        <div class="box-cart" >
            
        </div>

    </fieldset>
</div>
</form>

<ul class="link-list">
    <li>
        <form method="post" action="<?=$requestUrl?>/validation">
            <button type="submit" id="validate-order" class="button button-primary" > Valider la commande</button>  
        </form>
        <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
    </li>
</ul>

<script src="<?= $wwwUrl ?>/js/order.js"></script>





