 <h2><i class="fa fa-shopping-cart"></i> Passer une commande</h2>

<fieldset>
        <legend>Ajouter un article</legend>
        <ul>
            <li>
                <label for="productSelected">Nom :</label>
                <select id="productSelected" name="productSelected" width="200px">
                	<option></option>
                	<?php foreach ($products as $product): ?>
                    <option value="<?= $product["id"]; ?>"><?= $product["name"]; ?> </option>  
                        
                    <?php endforeach; ?>                        
                </select>

                <article id="meal-details" class="meal-details no-left-label">
                    <img src="" alt="">
                    <p></p>
                    <span>Prix : <strong></strong></span>
                </article>
            </li>
            <li>
                <label for="quantity">Quantité :</label>
                <input id="quantity" class="quantity" type="text" maxlength="2" name="quantity" data-name="Quantité" data-type="positive-integer" data-required>
            </li>
            <li>
                <button class="button button-primary no-left-label" type="submit">Ajouter</button>
            </li>
        </ul>
    </fieldset>

    <fieldset>
        <legend>Récapitulatif de la commande</legend>
        <section id="order-summary"></section>
    </fieldset>
</form>

<ul class="link-list">
    <li>
        <button id="validate-order" class="button button-primary" disabled>Valider la commande</button>
        <a class="button button-cancel small" href="/dev/resto/final/index.php">Annuler</a>
    </li>
</ul>


    <script src="<?= $wwwUrl ?>/js/order.js"></script>






